import { Geist, Geist_Mono } from "next/font/google";
import SuiProvider from "../providers/suiProvider";
import "./globals.css";
import Suimo from "../component/Header/suimo";
import SSS from "../component/Header/sss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SuiProvider>
          <Suimo />
          <SSS />
          {children}
        </SuiProvider>
      </body>
    </html>
  );
}
